### ISSUE TITLE
m3u-fix.sh doesn't handle URI encoding (%20) in file names

### ISSUE THREAD

**Issue by nodiscc** [mafrosis/mp3-scripts#1]
Some of my playlists actually store filenames URI-encoded, like

```
 /sftp%3Ahost%3Dtelecom.dmz.se%2Cport%3D822%2Cuser%3Dfalken/media/TERABOITE/Musique/Backup/Da Grassroots%20-%20Passage%20Trough%20Time/16%20Kenny%27s%20Theme.mp3
```

Notice the `%20̀` and `%27` used to escape whitespace and `'` characters. m3u-fix.sh should detect if the playlist uses this encoding and convert items to a "normal" encoding befor trying to find replacement files - else it will fail. I have a script to do this lying around somewhere, which is just just a perl one-liner. I will send a pull request if you're ok to include this.

**Comment by mafrosis** [comment]
Hey sure I'd welcome a pull request. I've actually been meaning to port all these scripts to python for a while now - bash has just too many pain points around character encodings and all the rest.

**Comment by nodiscc** [comment]
Hi, sorry for taking so long. Here is what I use to urldecode strings (yes it's a python script wrapped in a shell script :/ )

```
#!/bin/bash
urldecode(){
  python -c "import sys, urllib as ul; print ul.unquote_plus('$1')" ;
}

urldecode "$@"
```

I don't have much time now but hopefully you can do something with this.
